{% set version = "1.0.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pheatmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pheatmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pheatmap/pheatmap_{{ version }}.tar.gz
  sha256: 4ac34d4c5f787624f45cc98a97b8c28295c57eb635d1523554252c5a583142f7

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-gtable
    - r-scales
  run:
    - r-base
    - r-rcolorbrewer
    - r-gtable
    - r-scales

test:
  commands:
    - $R -e "library('pheatmap')"           # [not win]
    - "\"%R%\" -e \"library('pheatmap')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pheatmap
  license: GPL-2.0-only
  summary: Implementation of heatmaps that offers more control over dimensions and appearance.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - roryk

# Package: pheatmap
# Type: Package
# Title: Pretty Heatmaps
# Version: 1.0.12
# Date: 2018-12-26
# Author: Raivo Kolde
# Maintainer: Raivo Kolde <rkolde@gmail.com>
# Depends: R (>= 2.0)
# Description: Implementation of heatmaps that offers more control over dimensions and appearance.
# Imports: grid, RColorBrewer, scales, gtable, stats, grDevices, graphics
# License: GPL-2
# LazyLoad: yes
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-01-02 15:37:50 UTC; kolde
# Repository: CRAN
# Date/Publication: 2019-01-04 13:50:12 UTC
