travis:
  secure:
    BINSTAR_TOKEN: gZ8QYON6AhV9SVMtLBQuXt2y95G/Hk748AzTCDoAd4PafQgKZBy48yw1nYccIahZV4WPf+U+1AUgIcMpjnI3K7i81PctXPwEvKFM5wLfQaOvp/fL13vyAtyHqvLv0vcUN1cfVu/Qv4r38XywNd1+xbs9yuvPrcchQ5WDYgl2+12trDN27LpvLWKI1WAeE+mU7K6aXmyiBuN1pBFsbUGmFclUJNcPJWIg7gnrCBwWNIQqfqphcS0Vihy32e828i23OVE85jCiRCMzOQnB/aVtAXoEes0nX+QJrhOoSR8C0V2E8VvJvivwBZ4FJCwI6lyAs/y1rvgOOS+9dvp6tsIHV6YqRT1FmV2K92rYOpqdpENPf1oc/MJ0xgwqfpFdlG1lb4vXO2NzuzGFBIgrWTvOr/8TE7GoLt250rdykP5FImU5x0oeeLsuuoO3UXf7k9T4DauoGUqiJdFxlJ7ab4xB8rnufJ+X4W3Apg1GUBeVe5ElkPgVfI201lhej0gEFyp4KwyNDAo1McZImDB/krrk0g78I+kQXvyIZepxDBXIVXFw+bFZhuJEV3L+KoQ4O11AGjpq8m0DNdEg5TWeH9LCUS4vqyd95yUF1SItm7eSf7fVXn0q4FmD8j03biSIgFiN4mbEP37cYuPiyVbwfkTXnccaBZooH9mf1YmW1Cp50BM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
