travis:
  secure:
    BINSTAR_TOKEN: qCtUJSh9xy6mgBDsnGcxjy5s16QQPRZYARCp6TEKQRirH9f3/eY7wNXiLoiy49sU0UuWOSpwgR2znb98XuGxMOQtOJu4ytXH/mw89W5De/noSeY9IwOucqVLlFWv2ELbcgBLPXoBFxNHLJuexMSQw3qEMChd0Hedce0anEy7ffdXTVuiiSXsRDNcXxtDr2o+8T0wve4Bf+ERatjUkb2SdodI8Tx3bln0+9Keyudh0BpI7AvjyhUvXsYMhb1ygMZ3I9450ld/89WklbuYO02o8hiD6iaxPpSROKvZuSicCxgjSfDoMOOqHfnmGT7EJVifRqbkh7YTR8/FpsFsrPWCm0drGpVHcJXW2nzzi9mt3hriV+ue0QkDaRVg+aU2IDYFbkju7xgH03tOKTCR3PK9FzgqwwNpxCvX5g2hjldFZ0Mk8pz+VkkYDEGK0OrkwjfGhzmQhGjDcK/rQRBiS+9YgAc2myT2O7TQ2lN9+3uWADj7mWr6qxz9JNYRKgNUWoRruvdC1Oe1+kbqWXTun5VjTQTX5UJbicfxWfwY/2zi7CYoXgzYBbwx03cVhze1FEYs7sQsipmIeWrWzO/42zksMD1s4Nw3L3C8UlbdfRhmh0n3SQIxk504fa19b07VRj0mryzBPB7eHYtLZrxIsVTrE6C9uWPhomw9jOAITU9KznI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
