travis:
  secure:
    BINSTAR_TOKEN: NRripF+EdF8l7gZTvuB8CmJ2q9IxyFOGBKu47xXY+P70Xsw9uJLgHbgyGQ66ts4tBxE0Imk0SVMfE4KPErQBlO8c1q1TI/B6wM/wjjhwz7GuZYBewaopCl2TbeY28bdf+zWKEXlnXmRYuNdKh2xZHhx9HOg6yj84dFLHBXN2JNnuu8KX08I2tm9SlcwYm9eZtVCA92NAcKMOZVNYjggBJDnRPSxtNUgDsU7S9MoE57PvYipj3DENXbJttuAaQJIMojjj1qPgyH/7L8rdnC00rZar4Np/k/28qt3ivQxwHsPI6fRLHdi8ILf1eNjKLOn139FOQLbso1waX8nxxMQ9uVpIvf/F41eU4Bt8pt2XAEvOB6lOzy86f0EBh+0FmwjhRRb7edNUKZON6iS54q9TbZ1w2Th9w8WULQnLA9cEm2J4TmHWwSrbOSOQtOVUD+IyAxs6MoqfMnGm35m0LX2hsBNIPnc+/2bXFIz/SCrOlb6YJbsXuHJXKIN9mjIConJeNmAqazDPtXKcSvsjUQ4Fo/CUl1WYf8z/Eq7RwiWEeIYt7ONLvEx7CUu0DOSwB6jQKrSnJqTQrP87TxLeaHWnFZoky305ie3T0R2PKaz9OAEAP5OzTFR/uuIneA+jgi7pNnvg58vjidYsuUzTkxwIxpJNh5lyNceEZbmJIl6t4pg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
