appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J2eMetwjmEwr97Kcn8VJW9VGR+V6Zk1eIA3FviuJ7cb9QYz4GF3yTG1Cs5UoigZAUgA4g4m+gw+s8bWvBeuT9gGzHaMbvTVZeKlCgphKmXB5Y0E+ALMiK8Z2QW2xvcRHuvjwbbXfbRXYGsgsAJwdVNEC25ffnzY+tW4L8r5g+BUZHJy8T08ZD1ssDDUE2NNz+X2fDJ/3Rx0XDN4dgQNeOenMxtq9R2X/j6vCZxkFyrOFhTTpC9VakQDj1dRgT7mcSMbYytquJjMLAVIQFQIUSCFMDvsIVmvN4KGkT7Cd3r2n60uGOqNPNemHRHhmDCsQq9D6RH+eQ/iisS+6lYzgHQlBIIXyidxU3uf04X66Z1X3JUFv+6V7fy5LceeyQ99XFHED+f+cppR2Qr8Yy+LrTTzPnOq2/14/Uk4hY0o6tOw8Swd1putIkNnPx7Dfrx63q0hAaBELa0N9r+yxf5adpQAdPU/3/44w2vl9iKm9VLiCOIV9zEAoa4hvvAfmUsueQ9h/FPTyuZceHpdAkcf4bQZU460iADyq6GzEnu1D5Wf0Gv4Hq6FHikSLpZcCbzd9KvHh+tg/W1yRGg1993C+e8yuMGgaPsQTfmnj+FBwfKdie3JQX9o3S9qgEFNISkCDqQ9sv2QrljB/uoRATcVtkDUYBXqOeh/WvAZXzkvDWjU=}
bot:
  automerge: true
