travis:
  secure:
    BINSTAR_TOKEN: qNoTlzMA24VdwDLqeM/XrNl6tbTkf25cnvxs+7yGlPlqwLeReQa3zjZEWhZH1hG0GxvHPZlDGURv6CLeK/P+3FuYgche7hu38mvZnNsZ3VaRRzjWYojbkMQcNf3AwzHUilkIjvNlVmZQng6/jNn0MlrwE3kZSRxvuz2Wn3Sch385YDsM54EiM0SA07dSXsd5og2w59Nv1zYT74Izsc8IywPcDhugp87l64Tg3mRzQIA0RljfK2JEjZVxlPpd5z1O3rdLa8x/018TEk58j+8g7w0Ner7V456v9eniePOlk84DrqzuNOzSGzkMP0FlZkI0vinkRbx0Cmf1man3UD6C2B7Ehxc1wCKLoZY9L8QZeXhVKAb8Orvecoc28LcIocvideBEgC/7xNqbifOQEGEX/brXMEJuw9HSxjEmawFO01N3KkaMrKLNOY3HxfNx4x3e4zU8CI7MZM7bfLV1IklIvgvsnbPb7fx3KaaV29j+/Do0fGgu38Cdv6TT5OeZQY4cvvFRCOVnO0N4jqB9u73lekwFKSsZvOvgRwkMpY8oKPdwSMp8Atm9KrkKt9z/ZEWoNikkpDD5ckK6mYsLhRIGsfCCVEj8Q1Y8MV40pK7JlPWQ7F/KUHw3euG6Y4S+PxGyDcVHSyWmznmPmv8n9tZUyYKmpOf2HzppIB8hzKehxzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
