travis:
  secure:
    BINSTAR_TOKEN: Jr1aJMYGMZ6JQmztV4XS0Lz27EF2hxa0FicOvYOGsZ0eBTTFPpxN7DDIcHafQMLpGZwpfZ3zKy9aGv45W4tZBEtxqjfi+4H/Wl5CA+Y6AlekeoQtBQ+Qmsw8Q/W6KWdp71Pa0SKIvqd4k6qe59ZAW7WNOYj5tj072Y1Gd9sZdloQlTIwpX1PDoNCFxCBFara+fZS+eKCyix7maAgtUGVfopEmBbwCe+1ry0yieAOqsl+cOWqdwvMbk0aCgJBMJBjFkJZXYjP5Pdp/FRnnRogqN5vkxT3qaNmD54S5FNA4GltCXzX07l+6mfRN5yOC5zAhsF/idBHUU1mbAtuvbWVJSIXJolO1KNyIcO0TL0K3TCtRXAIuN0VXNkCDeBIwHiNVYDhC/K6qpLcExPxO8U3iUgDGqxYAR59imsxLKEXHiJOQEh6bXmN+L1Cf9KbEcl9n4wLs8B0HfUgPs2KYZq7azTIfdY4QMjYv9x9xlWrC0t/UgWVZ4iw+gd+MZhjE4a8QdSS9+FHv/mwHLUwrADMtvr74TmquSk05sCqDDzO34KyEs1gKIjB4I/IXxIqBudmFpPrq1ZzRD7lfE6uDx5pd73xcW+FtV3ufzVC24YabjoH7XVuG41eKZwqicmByxnOL8lpFYhMVFc/qs2/aAMAAAetlUYx3IbU0Ug04kD/+AY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
